# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title test_func
#'@description
#'To check whether build package successfully
#'@param x  mat
#'@param n int
#'@import Rcpp
#'@import RcppArmadillo
vec1 <- function(x, n) {
    .Call('_Gaussianst_vec1', PACKAGE = 'Gaussianst', x, n)
}

#'@title exponential_cov func
#'@description
#'calculate the exponential covariance function
#'@param x  vec
#'@param y vec
#'@useDynLib Gaussianst
#'@param params list for theta
#'@import Rcpp
#'@import RcppArmadillo
#'@export
exponential_cov <- function(x, y, params) {
    .Call('_Gaussianst_exponential_cov', PACKAGE = 'Gaussianst', x, y, params)
}

#'@title Gaussian_kernel func
#'@description
#'Calculate the Gaussian_kernel function
#'@param x  mat
#'@param y mat
#'@param kernel_width double
#'@useDynLib Gaussianst
#'@import Rcpp
#'@import RcppArmadillo
#'@export
Gaussian_kernel <- function(x, y, kernel_width) {
    .Call('_Gaussianst_Gaussian_kernel', PACKAGE = 'Gaussianst', x, y, kernel_width)
}

